### ISSUE TITLE
Implement auto-labeller

### ISSUE THREAD

**Issue by omh1280** [CesiumGS/cesium-concierge#11]
[`labelOpenedIssue`](https://github.com/AnalyticalGraphicsInc/cesium-concierge/blob/cc475f5c494933a4f5e990a0224401ff77f67835/index.js#L63) is partially implemented with poorly-written JavaScript and pseudo-code comments. It needs a good solution to the brains of the auto-labelling algorithm.

### The Problem
_Accurately pick and apply 1 or 2 labels for newly-opened PRs and issues._

### Input
- Available labels for the repository (https://api.github.com/repos/AnalyticalGraphicsInc/cesium/labels, for example)
- Comments, assignees, milestones, title/body of initial post

### Missing Information
As far as I can tell, there is no way to get these from the GitHub REST API:
- Commits/commit messages of the PR
- Files that have changed with the PR

Patrick initially wanted a machine-learning algorithm to pick labels. This seems impossible without knowing the files that have changed (not to mention my inexperience with machine learning).

### Possible Solution
The framework I currently have in [`labelOpenedIssue`](https://github.com/AnalyticalGraphicsInc/cesium-concierge/blob/cc475f5c494933a4f5e990a0224401ff77f67835/index.js#L63) is roughly:
- Scan the comments of a newly-opened pull request or issue -> 
- Find linked issues and pull requests ->
- Scan the linked issues and pull requests for __their__ labels -> 
- Collect them and order by frequency ->
- Choose a label from this smaller input space 
    - Still not sure how...

**Comment by pjcozzi** [comment]
From https://github.com/AnalyticalGraphicsInc/cesium/issues/5489

> To reduce manual paperwork, it would be cool to apply some simple "machine learning" to assign labels to GitHub issues and pull requests just like GitHub suggests reviewers for pull requests.
> 
> Pull requests should be easy to get mostly right based on the directory/files with the major changes.
> 
> Issues will be harder but could rely on keywords or even identifiers in example code.
> 
> For both pull requests and issues, we could have a friendly bot comment saying "I labeled this x and y. Please update if this is incorrect." It could even say different funny things based on its confidence level.
> 
> If nothing else is already out there, this could be a standalone project/repo that is configurable and perhaps useful to other projects, both our's and other's.

**Comment by pjcozzi** [comment]
Also see https://github.com/marketplace/issue-label-bot
